
from typing import List, Dict, Any, Optional, Union
import pandas as pd
from LimbleConnection.endpoint import LimbleEndpoint

class LimbleConnection:
    @property
    def routes_me_me(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_image_add_asset_main_image(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_image_delete_asset_main_image(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_asset_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_asset_suggested_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_asset_field_history(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_new_asset_suggested_field(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_update_asset_field_value(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_attach_field_to_asset(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_fields_delete_asset_field(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_files_delete_asset_log_file(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_files_add_asset_log_file(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_asset_logs(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_new_asset_log(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_update_asset_log(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_logs_delete_asset_log(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_batch_batch_update_asset_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_parts_asset_parts(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_assets(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_new_asset(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_patch_asset(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_delete_asset(self) -> LimbleEndpoint: ...
    @property
    def routes_assets_move_asset_to_another_location(self) -> LimbleEndpoint: ...
    @property
    def routes_locations_locations(self) -> LimbleEndpoint: ...
    @property
    def routes_locations_new_location(self) -> LimbleEndpoint: ...
    @property
    def routes_locations_update_location(self) -> LimbleEndpoint: ...
    @property
    def routes_locations_delete_location(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_images_add_part_image(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_images_delete_part_image(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_categories_create_part_category(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_categories_get_categories(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_categories_update_part_category(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_categories_delete_part_category(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_part_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_part_suggested_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_update_part_field_value(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_attach_field_to_part(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_new_part_suggested_field(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_fields_delete_part_field(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_logs_part_logs(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_logs_new_part_log(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_logs_update_part_log(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_logs_delete_part_log(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_logs_all_part_logs(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_purchasables_get_purchasables(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_parts(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_create_part(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_update_part(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_delete_part(self) -> LimbleEndpoint: ...
    @property
    def routes_parts_parts_usage(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_files_attach_a_file_to_an_invoice(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_files_delete_file_from_invoice(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_invoices(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_attach_an_invoice_to_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_delete_invoice_from_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_invoices_update_an_invoice(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_options_instruction_options(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_options_new_instruction_option(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_options_delete_instruction_option(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_options_update_instruction_option(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_task_instructions(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_new_task_instruction(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_update_task_instruction(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_delete_task_instruction(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_batch_task_instructions(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_instructions_get_task_instruction_by_id(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_images_task_instruction_image(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_images_delete_task_instruction_image(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_images_upload_task_main_image(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_images_delete_task_main_image(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_labor_task_labor(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_labor_get_labor_categories(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_parts_get_attached_parts(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_parts_get_all_attached_parts(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_parts_attach_part_to_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_parts_delete_part_from_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_comments_task_comments(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_comments_add_task_comments(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_tags_tags(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_tags_put_apply_task_tags(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_tags_delete_remove_task_tag(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_work_request_submissions_list_wr_submissions(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_new_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_update_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_delete_task(self) -> LimbleEndpoint: ...
    @property
    def routes_tasks_tasks(self) -> LimbleEndpoint: ...
    @property
    def routes_users_roles_get_user_roles(self) -> LimbleEndpoint: ...
    @property
    def routes_users_roles_add_user_to_role(self) -> LimbleEndpoint: ...
    @property
    def routes_users_roles_remove_role_from_user(self) -> LimbleEndpoint: ...
    @property
    def routes_users_teams_get_user_teams(self) -> LimbleEndpoint: ...
    @property
    def routes_users_teams_add_user_to_team(self) -> LimbleEndpoint: ...
    @property
    def routes_users_teams_remove_team_from_user(self) -> LimbleEndpoint: ...
    @property
    def routes_users_users(self) -> LimbleEndpoint: ...
    @property
    def routes_users_new_user(self) -> LimbleEndpoint: ...
    @property
    def routes_users_update_user(self) -> LimbleEndpoint: ...
    @property
    def routes_users_delete_user(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_vendor_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_vendor_suggested_fields(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_update_vendor_field_value(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_attach_field_to_vendor(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_new_vendor_suggested_field(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_fields_delete_vendor_field(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_images_add_vendor_image(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_images_delete_vendor_image(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_files_delete_vendor_log_file(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_files_add_vendor_log_file(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_vendor_logs(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_new_vendor_log(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_update_vendor_log(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_logs_delete_vendor_log(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_vendors(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_new_vendor(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_update_vendor(self) -> LimbleEndpoint: ...
    @property
    def routes_vendors_delete_vendor(self) -> LimbleEndpoint: ...
    @property
    def routes_roles_get_roles(self) -> LimbleEndpoint: ...
    @property
    def routes_roles_create_role(self) -> LimbleEndpoint: ...
    @property
    def routes_roles_update_role(self) -> LimbleEndpoint: ...
    @property
    def routes_roles_delete_role(self) -> LimbleEndpoint: ...
    @property
    def routes_teams_get_teams(self) -> LimbleEndpoint: ...
    @property
    def routes_teams_create_team(self) -> LimbleEndpoint: ...
    @property
    def routes_teams_update_team(self) -> LimbleEndpoint: ...
    @property
    def routes_teams_delete_team(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_items_get_purchase_order_items(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_items_new_purchase_order_item(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_items_update_purchase_order_item(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_items_delete_po_item(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_items_receive_po_item(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_comments_po_comments(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_comments_upload_po_comment_file(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_comments_delete_po_comment_file(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_comments_create_po_comment(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_comments_delete_po_comment(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_state_change_po_state(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_state_get_po_state_transitions(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_get_purchase_orders(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_new_purchase_order(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_update_purchase_order(self) -> LimbleEndpoint: ...
    @property
    def routes_purchase_orders_delete_po(self) -> LimbleEndpoint: ...
    @property
    def routes_general_ledgers_get_general_ledgers(self) -> LimbleEndpoint: ...
    @property
    def routes_general_ledgers_new_general_ledger(self) -> LimbleEndpoint: ...
    @property
    def routes_general_ledgers_update_general_ledger(self) -> LimbleEndpoint: ...
    @property
    def routes_general_ledgers_delete_general_ledger(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_steps_new_step(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_steps_delete_step(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_steps_get_steps(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_steps_update_step(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_get_budgets(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_new_budget(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_delete_budget(self) -> LimbleEndpoint: ...
    @property
    def routes_budgets_update_budget(self) -> LimbleEndpoint: ...
    @property
    def routes_priorities_get_priorities(self) -> LimbleEndpoint: ...
    @property
    def routes_priorities_update_priority(self) -> LimbleEndpoint: ...
    @property
    def routes_priorities_new_priority(self) -> LimbleEndpoint: ...
    @property
    def routes_priorities_delete_priority(self) -> LimbleEndpoint: ...
    @property
    def routes_tags_get_tags(self) -> LimbleEndpoint: ...
    @property
    def routes_tags_create_account_tag(self) -> LimbleEndpoint: ...
    @property
    def routes_tags_rename_account_tag(self) -> LimbleEndpoint: ...
    @property
    def routes_tags_delete_account_tag(self) -> LimbleEndpoint: ...
    @property
    def routes_statuses_statuses(self) -> LimbleEndpoint: ...
    @property
    def routes_statuses_create_status(self) -> LimbleEndpoint: ...
    @property
    def routes_statuses_update_status(self) -> LimbleEndpoint: ...
    @property
    def routes_statuses_delete_status(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_transactions_add_bill_item(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_transactions_bill_transactions(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_transactions_update_bill_transaction(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_transactions_bill_transaction(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_comments_bill_comments(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_comments_create_bill_comment(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_comments_upload_bill_comment_file(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_comments_delete_bill_comment_file(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_comments_delete_bill_comment(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_get_bills(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_new_bill(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_update_bill(self) -> LimbleEndpoint: ...
    @property
    def routes_bills_delete_bill(self) -> LimbleEndpoint: ...
    @property
    def routes_regions_regions(self) -> LimbleEndpoint: ...
    @property
    def routes_regions_create_region(self) -> LimbleEndpoint: ...
    @property
    def routes_regions_update_region(self) -> LimbleEndpoint: ...
    @property
    def routes_regions_delete_region(self) -> LimbleEndpoint: ...
    @property
    def routes_webhooks_get_webhooks(self) -> LimbleEndpoint: ...
    @property
    def routes_webhooks_delete_webhook(self) -> LimbleEndpoint: ...
    @property
    def routes_webhooks_new_webhook(self) -> LimbleEndpoint: ...
    @property
    def routes_webhooks_update_webhook(self) -> LimbleEndpoint: ...
    @property
    def routes_units_of_measure_get_units(self) -> LimbleEndpoint: ...
    @property
    def routes_units_of_measure_create_unit(self) -> LimbleEndpoint: ...
    @property
    def routes_units_of_measure_update_unit(self) -> LimbleEndpoint: ...